export function LeadMagnet() {
  return (
    <section className="lm" id="checklist"> <div className="container"> <div className="lm__inner"> <div className="lm__copy"> <div className="eyebrow  eyebrow--auto"> <span className="eyebrow__num mono eyebrow__num--auto"></span> <span className="eyebrow__line"></span> <span className="eyebrow__label mono">Ressource gratuite</span> </div>  <h2 className="lm__title">Pas encore prêt à demander un devis ?</h2> <p className="lm__text">
Téléchargez notre <strong>check-list gratuite</strong> : 12 points clés pour évaluer
          vous-même la sécurité et la conformité de votre installation électrique.
</p> <ul className="lm__points"> <li><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#16a34a" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12.5 4 4 10-10" /></svg> Tableau électrique & protections</li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#16a34a" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12.5 4 4 10-10" /></svg> Conformité NF C 15-100</li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#16a34a" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12.5 4 4 10-10" /></svg> Sécurité incendie & ERP</li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#16a34a" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12.5 4 4 10-10" /></svg> Économies d’énergie</li> </ul> </div> <div className="lm__card"> <div className="lm__cardhead"> <span className="lm__doc"><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#0e63ff" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z" /><path d="M14 3v5h5M9 13h6M9 16.5h6" /></svg></span> <div> <b>Check-list conformité</b> <span className="mono">PDF · 12 points · gratuit</span> </div> </div> <form action="/guides/merci" className="lm__form" method="POST" name="guide"> <input type="hidden" name="form-name" value="guide" /> <p className="hp" hidden><label>Ne pas remplir : <input name="bot-field" /></label></p> <label className="sr-only" htmlFor="lm-email">Votre e-mail</label> <div className="lm__row"> <input id="lm-email" name="email" type="email" required placeholder="votre@email.fr" autoComplete="email" /> <button type="submit" className="lm__btn">
Recevoir la check-list
<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg> </button> </div> <label className="lm__consent"> <input type="checkbox" name="consentement" required /> <span>J'accepte de recevoir la check-list et d'être éventuellement recontacté(e).</span> </label> </form> </div> </div> </div> </section>
  );
}
