const Star17 = (
  <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#ff6a1a" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m12 3.5 2.6 5.3 5.8.8-4.2 4.1 1 5.8L12 17l-5.2 2.7 1-5.8L3.6 9.6l5.8-.8z" /></svg>
);
const Star16 = (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#ff6a1a" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m12 3.5 2.6 5.3 5.8.8-4.2 4.1 1 5.8L12 17l-5.2 2.7 1-5.8L3.6 9.6l5.8-.8z" /></svg>
);

export function Testimonials() {
  return (
    <section className="tmo"><div className="container"><div className="tmo__head"><div className="eyebrow  eyebrow--auto"> <span className="eyebrow__num mono eyebrow__num--auto"></span> <span className="eyebrow__line"></span> <span className="eyebrow__label mono">Avis clients</span> </div> <h2 className="tmo__title">Ponctualité, sérieux et proximité.</h2><a href="https://www.pagesjaunes.fr" target="_blank" rel="noopener noreferrer" className="grating" aria-label="Note 5 sur 5 — 19 avis PagesJaunes"><span className="grating__stars" aria-hidden="true">{Star17}{Star17}{Star17}{Star17}{Star17}</span><span className="grating__txt"><b>5/5</b> · 19 avis PagesJaunes</span></a></div><div className="tmo__grid"><figure className="tmo__card"><div className="tmo__stars" role="img" aria-label="Note : 5 sur 5">{Star16}{Star16}{Star16}{Star16}{Star16}</div><blockquote className="tmo__quote">“Professionnel très sérieux dans son travail et sa relation au client. Je recommande.”</blockquote><figcaption className="tmo__author"><strong>Fabienne D.</strong><span>Cliente particulier · juin 2026</span></figcaption></figure><figure className="tmo__card"><div className="tmo__stars" role="img" aria-label="Note : 5 sur 5">{Star16}{Star16}{Star16}{Star16}{Star16}</div><blockquote className="tmo__quote">“L’électricien est arrivé exactement à l’heure prévue, très respectueux et rassurant. Le travail a été réalisé avec sérieux et efficacité. Notre problème a été résolu le jour même, un dimanche. Je recommande sans hésiter.”</blockquote><figcaption className="tmo__author"><strong>A. Chevallier</strong><span>Dépannage un dimanche · mars 2026</span></figcaption></figure><figure className="tmo__card"><div className="tmo__stars" role="img" aria-label="Note : 5 sur 5">{Star16}{Star16}{Star16}{Star16}{Star16}</div><blockquote className="tmo__quote">“Je recommande. Beau travail réalisé chez moi. Compétent et sympa.”</blockquote><figcaption className="tmo__author"><strong>Marceau L.</strong><span>Client particulier · février 2026</span></figcaption></figure></div></div></section>
  );
}
