import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Réalisations — Pro San Electricité à Beaugency (Loiret)",
  description: "Exemples de chantiers de Pro San Electricité dans le Loiret : rénovation électrique, motorisation de portail, interphonie et mise en sécurité.",
  alternates: { canonical: "/realisations" },
};

export default function RealisationsPage() {
  return (
    <main id="main" className="p-realisations">  <section className="container head"> <div className="eyebrow  ">  <span className="eyebrow__line"></span> <span className="eyebrow__label mono">Réalisations</span> </div>  <h1 className="head__h1">Nos réalisations</h1> <p className="head__lead">
Des chantiers représentatifs de mon savoir-faire en électricité et en automatisme, à Beaugency
      et dans le Loiret. Rénovation d&apos;installations, motorisation de portails, interphonie et mise
      en sécurité : chaque réalisation illustre ma méthode — diagnostic, solution adaptée et
      résultat concret.
</p> <p className="head__lead">
Particuliers, copropriétés, commerces ou collectivités : découvrez comment je réponds aux
      contraintes réelles de chaque client, dans le respect des normes et des délais.
</p> </section> <section className="container"> <div className="grid"> <a href="/realisations/renovation-pavillon-beaugency" className="rcard"> <div className="rcard__body"> <span className="mono rcard__meta">Rénovation · Beaugency (45190)</span> <h2 className="rcard__t">Rénovation électrique complète d&apos;un pavillon</h2> <p className="rcard__res">Installation entièrement reprise et mise aux normes, tableau neuf et repéré, sécurité rétablie. Le client dispose désormais d&apos;une installation fiable et durable, prête pour l&apos;avenir.</p> <span className="rcard__more">Lire l'étude de cas <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span> </div> </a><a href="/realisations/automatisme-portail-meung" className="rcard"> <div className="rcard__body"> <span className="mono rcard__meta">Automatisme · Meung-sur-Loire (45130)</span> <h2 className="rcard__t">Motorisation d&apos;un portail coulissant</h2> <p className="rcard__res">Portail motorisé, sécurisé et commandé à distance, avec entretien assuré pour une longévité maximale. Une entrée automatisée fiable, confortable au quotidien.</p> <span className="rcard__more">Lire l'étude de cas <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span> </div> </a><a href="/realisations/interphone-copropriete-clery" className="rcard"> <div className="rcard__body"> <span className="mono rcard__meta">Interphonie · Cléry-Saint-André (45370)</span> <h2 className="rcard__t">Interphone vidéo & mise en sécurité d&apos;une copropriété</h2> <p className="rcard__res">Interphone vidéo installé et parties communes remises en sécurité. Les résidents bénéficient désormais d&apos;un accès contrôlé, simple et durable au quotidien.</p> <span className="rcard__more">Lire l'étude de cas <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span> </div> </a> </div> </section> <section className="container real-outro"> <h2 className="real-outro__h">Votre projet sera ma prochaine réalisation</h2> <p>
Derrière chaque chantier, la même exigence : comprendre votre besoin, sécuriser l&apos;installation
      et tenir mes délais. Que vous soyez à Beaugency ou dans une commune voisine du Loiret, parlons
      de votre projet — <a href="/contact">demandez un devis gratuit</a> ou{" "}
<a href="/contact">contactez-moi</a>.
</p> </section> <section className="ctab"> <div className="container ctab__inner"> <div className="ctab__bg" aria-hidden="true"></div> <div className="ctab__copy"> <span className="mono ctab__eyebrow">Devis gratuit & sans engagement</span> <h2 className="ctab__title">Un projet électrique ? Recevez votre devis gratuit.</h2> <p className="ctab__text">Installation, rénovation, mise aux normes, automatisme de portail ou dépannage : confiez votre projet à un artisan du Loiret réactif et à l'écoute.</p> </div> <div className="ctab__actions"> <a href="/contact" className="btn btn--primary btn--lg "> Demander un devis <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg> </a>  <a href="tel:+33606489280" className="ctab__call"> <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6.5 3.5h3l1.2 4-2 1.4a12 12 0 0 0 5 5l1.4-2 4 1.2v3a1.6 1.6 0 0 1-1.7 1.6A15.5 15.5 0 0 1 4.9 5.2 1.6 1.6 0 0 1 6.5 3.5z" /></svg> 06 06 48 92 80 </a> </div> </div> </section>   </main>
  );
}
