import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "R\u00e9alisations \u2014 KB \u00c9lectricit\u00e9 G\u00e9n\u00e9rale \u00e0 Toulouse",
  description: "D\u00e9couvrez les chantiers et r\u00e9alisations de KB \u00c9lectricit\u00e9 G\u00e9n\u00e9rale \u00e0 Toulouse et sa m\u00e9tropole : tertiaire, commerces, copropri\u00e9t\u00e9s et industrie.",
  alternates: { canonical: "/realisations" },
};

export default function RealisationsPage() {
  return (
    <main id="main" className="p-realisations">  <section className="container head"> <div className="eyebrow  ">  <span className="eyebrow__line"></span> <span className="eyebrow__label mono">Réalisations</span> </div>  <h1 className="head__h1">Nos réalisations</h1> <p className="head__lead">
Des chantiers représentatifs de notre savoir-faire en courants forts et courants faibles, à
      Toulouse et dans la métropole. Mise en conformité de parties communes, relamping LED de
      bureaux, installation de bornes de recharge, remplacement de tableau : chaque réalisation
      illustre notre méthode — diagnostic, solution adaptée et résultat mesurable.
</p> <p className="head__lead">
Syndics, entreprises, commerces, copropriétés ou collectivités : découvrez comment nous
      répondons aux contraintes réelles de chaque client, dans le respect des normes et des délais.
</p> </section> <section className="container"> <div className="grid"> <a href="/realisations/mise-conformite-copropriete-blagnac" className="rcard"> <div className="rcard__body"> <span className="mono rcard__meta">Syndic de copropriété · Blagnac (31700)</span> <h2 className="rcard__t">Mise en conformité des parties communes d'une copropriété</h2> <p className="rcard__res">Installation conforme et sécurisée, réserves levées, attestations fournies pour l'assemblée générale. Le syndic dispose désormais d'un tableau lisible facilitant toute intervention future.</p> <span className="rcard__more">Lire l'étude de cas <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span> </div> </a><a href="/realisations/relamping-led-bureaux-colomiers" className="rcard"> <div className="rcard__body"> <span className="mono rcard__meta">Entreprise tertiaire · Colomiers (31770)</span> <h2 className="rcard__t">Relamping LED de 1 200 m² de bureaux</h2> <p className="rcard__res">Forte réduction de la consommation d'éclairage, maintenance quasi supprimée et confort visuel nettement amélioré. Retour sur investissement attendu en quelques années.</p> <span className="rcard__more">Lire l'étude de cas <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span> </div> </a><a href="/realisations/borne-irve-commerce-toulouse" className="rcard"> <div className="rcard__body"> <span className="mono rcard__meta">Commerce · Toulouse (31000)</span> <h2 className="rcard__t">Installation de bornes de recharge pour une flotte commerciale</h2> <p className="rcard__res">La flotte se recharge désormais sur site, en toute sécurité, avec une gestion intelligente de l'énergie. L'infrastructure est évolutive pour accueillir de nouveaux véhicules.</p> <span className="rcard__more">Lire l'étude de cas <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span> </div> </a> </div> </section> <section className="container real-outro"> <h2 className="real-outro__h">Votre projet sera notre prochaine réalisation</h2> <p>
Derrière chaque chantier, la même exigence : comprendre votre besoin, sécuriser l'installation
      et tenir nos délais. Que vous soyez à Toulouse ou dans une commune voisine, parlons de votre
      projet électrique — <a href="/devis">demandez un devis gratuit</a> ou
<a href="/contact">contactez-nous</a>.
</p> </section> <section className="ctab"> <div className="container ctab__inner"> <div className="ctab__bg" aria-hidden="true"></div> <div className="ctab__copy"> <span className="mono ctab__eyebrow">Devis gratuit & sans engagement</span> <h2 className="ctab__title">Un projet électrique ? Recevez votre devis gratuit.</h2> <p className="ctab__text">Installation, rénovation, mise en conformité, maintenance ou dépannage : confiez votre projet à une équipe toulousaine réactive et engagée.</p> </div> <div className="ctab__actions"> <a href="/devis" className="btn btn--primary btn--lg "> Demander un devis <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg> </a>  <a href="tel:+33651755039" className="ctab__call"> <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6.5 3.5h3l1.2 4-2 1.4a12 12 0 0 0 5 5l1.4-2 4 1.2v3a1.6 1.6 0 0 1-1.7 1.6A15.5 15.5 0 0 1 4.9 5.2 1.6 1.6 0 0 1 6.5 3.5z" /></svg> 06 51 75 50 39 </a> </div> </div> </section>   </main>
  );
}
